# Configuration minimale pour VoiceSkript
modules:
  fake_display: true
  fake_pathfinding: true
  random_stuff: true
  api: true
  request: true
  chunk_path: true

api_rest:
  # Port pour les requête
  port: 443
  # Clef API secrète à utiliser dans les requêtes
  key: ""
  
  use_https: true
  # Chemin vers le certificat et la clef privée, generate the certificat by yourself or disable use_https.
  certificate: "certificate.crt"
  private_key: "private.key"

chunkpath:
  # Dossier (dans le dossier du plugin) contenant les bases de données de chemins, une par monde
  database_folder: "chunkpath-data"
  # Dossier de base des dimensions du monde (relatif au dossier du serveur, ou absolu).
  # Les fichiers région sont lus dans <world_folder>/<overworld|the_nether|the_end>/region
  world_folder: "world/dimensions/minecraft"